name: MSBuild

on: push

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:

    - uses: actions/checkout@v2

    - uses: microsoft/setup-msbuild@v1

    - uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore PCAxis.PX-Web_with_tests.sln

    - name: Build the application
      run: msbuild /p:Configuration=$env:Configuration  PCAxis.PX-Web_with_tests.sln
      env:
        Configuration: ${{ matrix.configuration }}
